#debug: false
server:
  port: 8081
  servlet:
    context-path: /combination
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  #  devtools:
  #    restart:
  #      enabled: true  #设置开启热部署
  #  freemarker:
  #    cache: false    #页面不加载缓存，修改即时生效
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  datasource:
    readSize: 1
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      write:
        url: jdbc:mysql://10.104.20.123:3306/ucar_combination_test1?useUnicode=true&characterEncoding=UTF-8&useSSL=false&&allowMultiQueries=true&serverTimezone=GMT%2B8&&zeroDateTimeBehavior=convertToNull
        username: developer
        password: developer1015
        #        url: jdbc:mysql://127.0.0.1:3306/ucar_combination_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&&allowMultiQueries=true&serverTimezone=GMT%2B8&&zeroDateTimeBehavior=convertToNull
        #        username: root
        #        password: ucarinc
        read:
          url: jdbc:mysql://10.104.20.123:3306/ucar_combination_test1?useUnicode=true&characterEncoding=UTF-8&useSSL=false&&allowMultiQueries=true&serverTimezone=GMT%2B8&&zeroDateTimeBehavior=convertToNull
          username: developer
          password: developer1015
      #        url: jdbc:mysql://127.0.0.1:3306/ucar_combination_test1?useUnicode=true&characterEncoding=UTF-8&useSSL=false&&allowMultiQueries=true&serverTimezone=GMT%2B8&&zeroDateTimeBehavior=convertToNull
      #        username: root
      #        password: ucarinc
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
    type-aliases-package: com.ucar.combination.model.po

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  main:
    allow-bean-definition-overriding: true

  application:
    name: spirng-boot-mail
  # 配置邮件发送
  mail:
    host: smtp.qq.com
    username: 2207843123@qq.com
    password: ntnaonsghyuadieb
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
mybatis:
  typeAliasesPackage: com.ucar.combination.model
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case=true:
mail:
  fromMail:
    addr: 2207843123@qq.com
jpa:
  data: MYSQL
  show-sql: true
  hibernate:
    ddl-auto: update
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=contSql


